services:
  ollama-service:
    restart: always
    image: ollama/ollama
    tty: true
    expose:
      - "11434"
    ports:
      - "127.0.0.1:11434:11434"
    labels:
      - "traefik.http.routers.ollama-service.rule=Host(`${HOST}.nip.io`)"
      - "traefik.http.routers.ollama-service.entrypoints=websecure"
      - "traefik.http.routers.ollama-service.tls.certresolver=myresolver"
      - "traefik.http.middlewares.main-auth.basicauth.users=${CREDENTIALS}"
      - "traefik.http.routers.ollama-service.middlewares=main-auth@docker"
      - "traefik.http.services.ollama-service.loadbalancer.server.port=11434"
    environment:
      OLLAMA_KEEP_ALIVE: "-1"
      VERBOSE: "${VERBOSE:-0}"
    runtime: nvidia
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - "./.ollama:/root/.ollama"

  reverse-proxy:
    image: traefik:v2.4
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=socialgroovybot@fabrique.social.gouv.fr"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"
