services:
  ollama-service-1:
    restart: always
    image: ollama/ollama
    tty: true
    expose:
      - "11434"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ollama-service.rule=Host(`${HOST}.nip.io`)"
      - "traefik.http.routers.ollama-service.entrypoints=websecure"
      - "traefik.http.routers.ollama-service.tls.certresolver=myresolver"
      - "traefik.http.middlewares.main-auth.basicauth.users=${CREDENTIALS}"
      - "traefik.http.routers.ollama-service.middlewares=main-auth@docker"
      - "traefik.http.services.ollama-service.loadbalancer.server.port=11434"
    environment:
      OLLAMA_KEEP_ALIVE: "-1"
    runtime: nvidia
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    volumes:
      - "./.ollama-service-1:/root/.ollama"
    networks:
      - ollama-network

  ollama-service-2:
    restart: always
    image: ollama/ollama
    tty: true
    expose:
      - "11434"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ollama-service.rule=Host(`${HOST}.nip.io`)"
      - "traefik.http.routers.ollama-service.entrypoints=websecure"
      - "traefik.http.routers.ollama-service.tls.certresolver=myresolver"
      - "traefik.http.middlewares.main-auth.basicauth.users=${CREDENTIALS}"
      - "traefik.http.routers.ollama-service.middlewares=main-auth@docker"
      - "traefik.http.services.ollama-service.loadbalancer.server.port=11434"
    environment:
      OLLAMA_KEEP_ALIVE: "-1"
    runtime: nvidia
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]
    volumes:
      - "./.ollama-service-2:/root/.ollama"
    networks:
      - ollama-network

  nvidia-monitor:
    privileged: true
    build: ./nvidia-monitor
    restart: always
    expose:
      - "5000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nvidia-monitor.rule=Host(`gpu.${HOST}.nip.io`)"
      - "traefik.http.routers.nvidia-monitor.entrypoints=websecure"
      - "traefik.http.routers.nvidia-monitor.tls.certresolver=myresolver"
      - "traefik.http.middlewares.main-auth.basicauth.users=${CREDENTIALS}"
      - "traefik.http.routers.nvidia-monitor.middlewares=main-auth@docker"
      - "traefik.http.services.nvidia-monitor.loadbalancer.server.port=5000"
    volumes:
      - "/usr/bin/nvidia-smi:/usr/bin/nvidia-smi:ro"
    devices:
      - "/dev/nvidia0:/dev/nvidia0"
      - "/dev/nvidia1:/dev/nvidia1"
    networks:
      - ollama-network

  reverse-proxy:
    image: traefik:v3.2
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=socialgroovybot@fabrique.social.gouv.fr"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - ollama-network

networks:
  ollama-network:
    driver: bridge
