services:
  vllm-cpu-env:
    image: vllm/vllm-openai:latest
    environment:
      HUGGING_FACE_HUB_TOKEN: "${HUGGING_FACE_HUB_TOKEN}"
    command:
      - "--model=${MODEL:-mistralai/Mistral-7B-v0.1}"
      - "--tensor-parallel-size=4"
      - "--dtype=half" # https://github.com/vllm-project/vllm/issues/1157
    expose:
      - "8000"
    labels:
      - "traefik.http.routers.vllm-cpu-env.rule=Host(`${HOST}.nip.io`)"
      - "traefik.http.routers.vllm-cpu-env.entrypoints=websecure"
      - "traefik.http.routers.vllm-cpu-env.tls.certresolver=myresolver"
      - "traefik.http.middlewares.main-auth.basicauth.users=${CREDENTIALS}"
      - "traefik.http.routers.vllm-cpu-env.middlewares=main-auth@docker"
    runtime: nvidia  # Set the desired runtime for GPU support
    ipc: host  # Set the IPC namespace to host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  reverse-proxy:
    image: traefik:v2.4
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=socialgroovybot@fabrique.social.gouv.fr"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"
