services:
  vllm-cpu-env:
    image: ghcr.io/socialgouv/docker/vllm-cpu-env:latest
    expose:
      - "8000"
    labels:
      - "traefik.http.routers.vllm-cpu-env.rule=Host(`${HOST}.nip.io`)"
      - "traefik.http.routers.vllm-cpu-env.entrypoints=websecure"
      - "traefik.http.routers.vllm-cpu-env.tls.certresolver=myresolver"
      - "traefik.http.middlewares.main-auth.basicauth.users=${CREDENTIALS}"
      - "traefik.http.routers.vllm-cpu-env.middlewares=main-auth@docker"

  reverse-proxy:
    image: traefik:v2.4
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=socialgroovybot@fabrique.social.gouv.fr"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"
