services:
  ollama-service-1:
    restart: always
    image: ollama/ollama
    tty: true
    expose:
      - "11434"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ollama-service.rule=Host(`${HOST}.nip.io`)"
      - "traefik.http.routers.ollama-service.entrypoints=websecure"
      - "traefik.http.routers.ollama-service.tls.certresolver=myresolver"
      - "traefik.http.middlewares.main-auth.basicauth.users=${CREDENTIALS}"
      - "traefik.http.routers.ollama-service.middlewares=main-auth@docker"
      - "traefik.http.services.ollama-service.loadbalancer.server.port=11434"
    environment:
      OLLAMA_KEEP_ALIVE: "-1"
      # CUDA_VISIBLE_DEVICES: "2"
      # NVIDIA_VISIBLE_DEVICES: "0"
    runtime: nvidia
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              # count: all
              capabilities: [gpu]
    volumes:
      - "./.ollama-service-1:/root/.ollama"
    networks:
      - ollama-network

  ollama-service-2:
    restart: always
    image: ollama/ollama
    tty: true
    expose:
      - "11434"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ollama-service.rule=Host(`${HOST}.nip.io`)"
      - "traefik.http.routers.ollama-service.entrypoints=websecure"
      - "traefik.http.routers.ollama-service.tls.certresolver=myresolver"
      - "traefik.http.middlewares.main-auth.basicauth.users=${CREDENTIALS}"
      - "traefik.http.routers.ollama-service.middlewares=main-auth@docker"
      - "traefik.http.services.ollama-service.loadbalancer.server.port=11434"
    environment:
      OLLAMA_KEEP_ALIVE: "-1"
    runtime: nvidia
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]
    volumes:
      - "./.ollama-service-2:/root/.ollama"
    networks:
      - ollama-network

  reverse-proxy:
    image: traefik:v3.2
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=socialgroovybot@fabrique.social.gouv.fr"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - ollama-network

networks:
  ollama-network:
    driver: bridge
