services:
  llm-service:
    restart: always
    image: ghcr.io/socialgouv/llm-inference-server:main
    environment:
      HUGGING_FACE_HUB_TOKEN: "${HUGGING_FACE_HUB_TOKEN}"
      S3_ACCESS_KEY_ID: "${S3_ACCESS_KEY_ID}"
      S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY}"
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
      S3_MODEL_PATH: ${S3_MODEL_PATH}
    expose:
      - "8000"
    ports:
      - "127.0.0.1:8000:8000"
    labels:
      - "traefik.http.routers.vllm-service.rule=Host(`${HOST}.nip.io`)"
      - "traefik.http.routers.vllm-service.entrypoints=websecure"
      - "traefik.http.routers.vllm-service.tls.certresolver=myresolver"
      - "traefik.http.middlewares.main-auth.basicauth.users=${CREDENTIALS}"
      - "traefik.http.routers.vllm-service.middlewares=main-auth@docker"
    runtime: nvidia  # Set the desired runtime for GPU support
    ipc: host  # Set the IPC namespace to host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /opt/vllm/models:/app/models
    # healthcheck:
    #   test: curl --fail http://localhost:8000/v1/models || exit 1
    #   interval: 10s
    #   timeout: 30s
    #   retries: 60
    #   start_period: 60s

  reverse-proxy:
    image: traefik:v2.4
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=socialgroovybot@fabrique.social.gouv.fr"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"

  # autoheal:
  #   image: willfarrell/autoheal:latest
  #   tty: true
  #   restart: always
  #   environment:
  #     - AUTOHEAL_INTERVAL=60
  #     - AUTOHEAL_START_PERIOD=300
  #     - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock