name: Delete instance

on:
  workflow_dispatch:

jobs:
  delete-instance:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: poetry install

      - name: Run Python script
        run: poetry run python main.py delete
